export const QUERY_KEYS = {
  ME: "me",
  BANKS: "banks",
  TRANSACTIONS: "transactions",
  TRANSACTION_DETAIL: "transaction-detail",
  TRANSACTION_SUMMARY: "transaction-summary",
  UNVERIFIED_TRANSACTIONS: "unverified-transactions",
  BUDGETS: "budgets",
  BUDGET_DETAIL: "budget-detail",
  BUDGET_SUGGESTIONS: "budget-suggestions",
  GOALS: "goals",
  GOAL_DETAIL: "goal-detail",
  INSIGHTS: "insights",
  EXCHANGE_RATES: "exchange-rates",
  EMAIL_CONNECTIONS: "email-connections",
  EMAIL_CONNECTION_DETAIL: "email-connection-detail",
  GMAIL_AUTH_URL: "gmail-auth-url",
  CHART_DATA: "chart-data",
} as const;
