import { CategoryType } from "./transactions.interface";

export const CATEGORY_LABELS: Record<CategoryType, string> = {
  peer_to_peer_transfer: "Peer Transfer",
  business_payment: "Business Payment",
  subscriptions: "Subscriptions",
  entertainment_leisure: "Entertainment",
  mobile_internet: "Mobile & Internet",
  utilities: "Utilities",
  groceries: "Groceries",
  retail_ecommerce: "Retail & Shopping",
  dining_food_delivery: "Dining & Delivery",
  transport: "Transport",
  fuel_auto: "Fuel & Auto",
  travel: "Travel",
  bank_charges: "Bank Charges",
  currency_conversion: "FX Conversion",
  salary_wages: "Salary & Wages",
  refunds_reimbursements: "Refunds",
  healthcare: "Healthcare",
  education: "Education",
  charity_donations: "Charity",
  cash_withdrawal: "Cash Withdrawal",
  uncategorized: "Uncategorized",
};

export const CATEGORY_ICON_NAMES: Record<CategoryType, string> = {
  peer_to_peer_transfer: "people-outline",
  business_payment: "briefcase-outline",
  subscriptions: "tv-outline",
  entertainment_leisure: "game-controller-outline",
  mobile_internet: "wifi-outline",
  utilities: "flash-outline",
  groceries: "basket-outline",
  retail_ecommerce: "bag-handle-outline",
  dining_food_delivery: "restaurant-outline",
  transport: "car-outline",
  fuel_auto: "car-sport-outline",
  travel: "airplane-outline",
  bank_charges: "card-outline",
  currency_conversion: "repeat-outline",
  salary_wages: "wallet-outline",
  refunds_reimbursements: "return-down-back-outline",
  healthcare: "heart-outline",
  education: "school-outline",
  charity_donations: "heart-circle-outline",
  cash_withdrawal: "cash-outline",
  uncategorized: "ellipsis-horizontal-outline",
};

export const ALL_CATEGORIES: CategoryType[] = [
  "peer_to_peer_transfer",
  "business_payment",
  "subscriptions",
  "entertainment_leisure",
  "mobile_internet",
  "utilities",
  "groceries",
  "retail_ecommerce",
  "dining_food_delivery",
  "transport",
  "fuel_auto",
  "travel",
  "bank_charges",
  "currency_conversion",
  "salary_wages",
  "refunds_reimbursements",
  "healthcare",
  "education",
  "charity_donations",
  "cash_withdrawal",
  "uncategorized",
];
